### ISSUE TITLE
Can't save folders

### ISSUE THREAD

**Issue by LopeMonkey** [Myster-Tee/NxFileViewer#1]
Hello,

I am trying to save a folder, specifically a titles folder, but it won't let me save it. I am not sure if this is do to it showing the folder size is 0b or what, but I can go into each individual folder in the titles folder, and download the individually, but there are several, and I would like to just be able to either right click and save the entire titles folder, or just drag the folder and drop it somewhere. Is this possible? Thank you

PS: I have the keys all loaded correctly.

**Comment by Myster-Tee** [comment]
Hi, I already saw this bug. It will be fixed in the next version.

**Comment by Myster-Tee** [comment]
Fixed in version 2.2.0

**Comment by LopeMonkey** [comment]
Thank you!
