### ISSUE TITLE
[Request] Display Build ID on main screen

### ISSUE THREAD

**Issue by DARKFiB3R** [Myster-Tee/NxFileViewer#12]
It would be nice if the Build ID was displayed on the main window under General Info, rather than having to go digging for it, and then carefully selecting the first 16 digits.

Thanks.

**Comment by Myster-Tee** [comment]
Why is the Build ID so important ?

**Comment by DARKFiB3R** [comment]
Sorry for the late reply.

Honestly, I can't remember. Obviously I must have needed it for some reason. Some sort of jiggery pokery, no doubt.

**Comment by Myster-Tee** [comment]
Already implemented
