### ISSUE TITLE
Feature Request: Commandline option

### ISSUE THREAD

**Issue by SMAW** [Myster-Tee/NxFileViewer#15]
I would love to use this tool using commandline, so I can write a script and do batch verifications

**Comment by Myster-Tee** [comment]
Which kind of command?

**Comment by SMAW** [comment]
To output all information that are in the GUI, so all textfields (like titleID, Name, etc) and ultimately it would be awesome if there would be an verify option, so the commandline will return if the file had a good signature/hash validation.

**Comment by Myster-Tee** [comment]
For hash/signature, you can use hactool or hactoolnet.
I already though of developing some kind of bulk analysis functions with export to CSV, but probably not from command line, as this app is not by nature a *console app*.
