### ISSUE TITLE
.NET missing frameworks

### ISSUE THREAD

**Issue by PaulStranger** [Myster-Tee/NxFileViewer#16]
v 2.6.1.
I launched the application and saw a message that there were no required framework components. I downloaded the .NET installer, which confirmed to me that I have all the necessary components of version 4.8. After clicking "Yes" (сyrillic ДА) nothing happens.
NUC12
Win 10/64 / 22H2 / 19045.3448

<img width="314" alt="notify-NET" src="https://github.com/Myster-Tee/NxFileViewer/assets/34210762/27142d18-2c17-43ab-9b6a-38e39feb65f5">

___
UPD: solved. need to install .NET 6.0 Desktop Runtime (v6.0.22):
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.22-windows-x86-installer?cid=getdotnetcore

**Comment by Myster-Tee** [comment]
Yes it is written in the documentation
