### ISSUE TITLE
Add supported Windows versions to the README

### ISSUE THREAD

**Issue by dtrunk90** [Myster-Tee/NxFileViewer#17]
I've set up a Win 7 VM just to run this tool since it's not available for Linux.
But this tool does nothing.
No error message, nothing.
.NET Runtime 6 is installed.

With a Win 10 VM everything works fine though.
Please add the supported Windows versions to the README file.

**Comment by Myster-Tee** [comment]
Thanks for reporting.
This is strange, as .NET 6 is supported for Windows 7 SP1.
Anyway, next release will be based on .NET 7 which is officially not supported by Windows 7 and 8.1.
