### ISSUE TITLE
Renaming wrong because a patch is seen as an application

### ISSUE THREAD

**Issue by JaySea77** [Myster-Tee/NxFileViewer#19]
In my patterns I add [Base] for application and [Update] for patch.
I noticed that I found an item which was of type Application while the version was not 0.
![application_patch](https://github.com/Myster-Tee/NxFileViewer/assets/31116706/9df81cbc-c1a4-439b-8860-04c661cf9ae1)

Is the version wrong or is the type wrong or is something else the issue here?

**Comment by x7l7j8cc** [comment]
@JaySea77 Sometimes games on Cartridges or eShop the Base isnt always 0.
And in the case of this game the BASE is 65536.

**Comment by JaySea77** [comment]
First time I have seen this on a none xci actualy.

Jan Coenen Verstuurd vanaf mijn IPhone

**Comment by x7l7j8cc** [comment]
@JaySea77 Yes, unusual but normal sometimes. ;)

**Comment by TheExpertNoob** [comment]
This is what is considered a sparse title. They usually include a day0 patch included in the base title. They are few, but got me the first time I saw one. I haven't been able to find much info about them.

**Comment by Myster-Tee** [comment]
@JaySea77 as explained before, in some rare cases, the base file version can be other than 0. Those files are known as sparse.
But did you really observed a renaming issue related to sparse files? Or you just opened this issue because you got surprised to see a base file with version other than 0?

**Comment by JaySea77** [comment]
I was just surprised. There was nothing wrong. Also with compressing these files, the nsz usually isn't smaller than the nsp.

**Comment by Myster-Tee** [comment]
Ok, thanks. I then close the issue.
