### ISSUE TITLE
Re-word "Error" Messages

### ISSUE THREAD

**Issue by harvestry-of-ghosts** [Myster-Tee/NxFileViewer#28]
When keys are loaded the app gives the following messages:

Failed to match key device_key_4x
Failed to match key eticket_rsa_kek_source
Failed to match key eticket_rsa_kekek_source
Failed to match key save_mac_key
Failed to match key ssl_rsa_kek_source
Failed to match key ssl_rsa_kekek_source
Failed to match key ssl_rsa_key

I don't believe there is any kind of actual failure or error going on. Isn't this just saying there are extra keys that are not needed? Perhaps the messages should be reworded from "Failed to match key" to "Found redundant key".

**Comment by Myster-Tee** [comment]
Sorry, those messages are coming from LibHac, I can't change them
