### ISSUE TITLE
Update app to use NET 8 as NET 7 has reached end of life

### ISSUE THREAD

**Issue by harvestry-of-ghosts** [Myster-Tee/NxFileViewer#29]
Request to use NET 8 for the app. NET 7 reached end of life on June 11th. NET 8 is supported until the end of 2026.

**Comment by 0x7A2C9E5D** [comment]
This upgrade is very simple. Here are the upgraded files.
[NxFileViewer.zip](https://github.com/user-attachments/files/16043018/NxFileViewer.zip)

**Comment by harvestry-of-ghosts** [comment]
> This upgrade is very simple. Here are the upgraded files. [NxFileViewer.zip](https://github.com/user-attachments/files/16043018/NxFileViewer.zip)

Why three extra files are needed that are not present in the "official" build?

NxFileViewer.runtimeconfig.json
NxFileViewer.deps.json
NxFileViewer.dll

**Comment by 0x7A2C9E5D** [comment]
This is due to the different packaging methods. The dll file is the actual program .The other two are configuration files, and deleting them may cause the program to not work.

**Comment by 0x7A2C9E5D** [comment]
This should be the way you expect to be packed
![image](https://github.com/Myster-Tee/NxFileViewer/assets/7698849/b38adc5c-2ffd-48de-9256-825b54c1315d)
[NxFileViewer_v2.7.0_x64.zip](https://github.com/user-attachments/files/16047411/NxFileViewer_v2.7.0_x64.zip)
[NxFileViewer_v2.7.0_x86.zip](https://github.com/user-attachments/files/16047412/NxFileViewer_v2.7.0_x86.zip)

**Comment by 0x7A2C9E5D** [comment]
The following command was used to publish：
x64:dotnet publish -r win-x64 -p:PublishSingleFile=true -p:PublishSelfContained=false
x86:dotnet publish -r win-x86 -p:PublishSingleFile=true -p:PublishSelfContained=false

**Comment by dhlalit11** [comment]
@ssc19940105 can you please publish a self contained build.. i am trying to run this on ubuntu with wine but i cannot install .net runtime in wine as i am using wow64 mode which is very experimental right now

Thanks in advance

**Comment by Myster-Tee** [comment]
Done in v3.0.0
