### ISSUE TITLE
Hash for nsz files not working!

### ISSUE THREAD

**Issue by pwr-krn** [Myster-Tee/NxFileViewer#3]
Hash for nsz files not working!
It always shows only "Error"
i tried several files, self compressed from nsp files, at compression level 22 and 18.
Could you please check and fix it?
Thank you.

**Comment by pwr-krn** [comment]
Now with new version 2.5.0 it changed from "Error" to "invalid"!

**Comment by Myster-Tee** [comment]
Because NSZ contains compressed NCA, which are not yet supported in LibHac.

**Comment by JaySea77** [comment]
shouldn't hactool v0.19.0 support this? The hash check is still not working
