### ISSUE TITLE
Double folder content view v2.5.0

### ISSUE THREAD

**Issue by ElkinGuns-Jr** [Myster-Tee/NxFileViewer#5]
The folder content shows without clicking on it. when i click on the folder the folder content shows twice.

**Comment by Myster-Tee** [comment]
Do you have a screenshot?

**Comment by ElkinGuns-Jr** [comment]
![image](https://user-images.githubusercontent.com/94803417/160650314-4498abf1-0748-4d1d-91b8-2e7cff377d99.png)

the same file on diferent version.

**Comment by Myster-Tee** [comment]
I confirm your observations, I'm gonna check that soon! 
Thanks ;)

**Comment by Myster-Tee** [comment]
Fixed in v2.6.1.
