### ISSUE TITLE
Missing framework issue

### ISSUE THREAD

**Issue by Cylent1** [Myster-Tee/NxFileViewer#6]
Hello...
I run window 11 and It won't run for me.  It keeps telling me it won't run without the missing frameworks for NET.
I have downloaded the NET Framework runtimes v5 and v6 for both x64 and x86 from the github page for this app and nothing works.
Am I missing something?

**Comment by topy777** [comment]
me too.

**Comment by Maverynthia** [comment]
I get this error as well. Installed .NET 6.0.4 x64 AND x86

**Comment by khaslid** [comment]
> I get this error as well. Installed .NET 6.0.4 x64 AND x86
the latest version .NET is 6.0.2 and preview .NET 7.0.1 >_<

**Comment by khaslid** [comment]
download here: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.2-windows-x64-installer
install _windowsdesktop-runtime-6.0.2-win-x64.exe_, not _dotnet-runtime-6.0.2-win-x86.exe_.
click "Download x64" below "Run desktop apps" ，not“Run console apps” !

**Comment by topy777** [comment]
It started, but it's not working properly. It freezes.

**Comment by Myster-Tee** [comment]
I close this issue as it is a very isolated case, probably due to a bad installation (or configuration).
