### ISSUE TITLE
tool shows No NCA

### ISSUE THREAD

**Issue by ghost** [Myster-Tee/NxFileViewer#7]
if i open an nsp it shows just "No NCA".
file is viewable in XCI Explorer (tested as test).

• Failed to load NCA file: Unable to decrypt NCA header. The file is not an NCA file or the header key is incorrect.
• Failed to load NCA file: Unable to decrypt NCA header. The file is not an NCA file or the header key is incorrect.
• Failed to load NCA file: Unable to decrypt NCA header. The file is not an NCA file or the header key is incorrect.
• Failed to load NCA file: Unable to decrypt NCA header. The file is not an NCA file or the header key is incorrect.
• No CNMT entry found!

 (key files are valid)

how can this be fixed?
br

**Comment by ghost** [comment]
new version , refreshed key file storage... reset it now works again oO
oh man... how about a error message no key file loaded ? ^^

**Comment by Myster-Tee** [comment]
Done in v2.7.0 :)
