### ISSUE TITLE
Unable to extract romfs for update patch

### ISSUE THREAD

**Issue by hgh32** [Myster-Tee/NxFileViewer#8]
![issue](https://user-images.githubusercontent.com/39622638/191845353-080de632-d3fa-460e-b1b8-8e38f80b7df3.PNG)
The section 1 right-click menu of the update patch does not have the “save section content” option
Is this a bug?

**Comment by hgh32** [comment]
https://github.com/SciresM/hactool/issues/81
I seem to have found the problem, the romfs of the update patch seems to be a special BKTR partition, which can be successfully extracted using hactool, but I don't know if libhac supports it

**Comment by Myster-Tee** [comment]
This is not really a bug, actually NxFileViewer shows the raw structure of a file (patch or base).
A patch contains no file, but information for patching (updating) a base file, this is what you can't save the content.
I plan to support opening a base file with a patch file (libhac supports it).
